"""initial migration

Revision ID: 083856d73ffd
Revises: bf5a81ec94ac
Create Date: 2016-12-16 19:47:47.276487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083856d73ffd'
down_revision = 'bf5a81ec94ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
